title: 'Phil réalise son rêve'
default_lang: fr
author:
  name: Philippe
  email: maxime.hersand@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Philippe et son voyage'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
